name: Chocolatine

on:
  push:
    branches: [ master, main ]

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Install dependencies
          run: sudo dnf install -y libconfig libconfig-devel
        - name: Compile program
          run: ./run.sh
          timeout-minutes: 2
        - name: Clean repository
          run: ./clean.sh